import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { notFound } from "next/navigation";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { routing } from "@/i18n/routing";
import { buildAlternates, ogLocale, localizedUrl } from "@/lib/seo";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: 'swap',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: 'swap',
});

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  return {
    metadataBase: new URL("https://resumecraftor.com"),
    title: {
      default: "ResumeCraftor — Free ATS-Friendly Resume Builder",
      template: "%s | ResumeCraftor",
    },
    description: "Build a professional, ATS-optimized resume in minutes with ResumeCraftor's free online resume builder. Pick a template, customize, and download a polished PDF.",
    applicationName: "ResumeCraftor",
    alternates: buildAlternates("/", locale),
    robots: {
      index: true,
      follow: true,
    },
    icons: {
      icon: [
        { url: "/favicon.ico", sizes: "any" },
        { url: "/favicon-32.png", type: "image/png", sizes: "32x32" },
      ],
      apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
    },
    openGraph: {
      // Social image is generated by app/[locale]/opengraph-image.tsx (1200x630).
      title: "ResumeCraftor - Professional Resume Builder",
      description: "Create professional, ATS-optimized resumes in minutes with ResumeCraftor.",
      url: localizedUrl("/", locale),
      siteName: "ResumeCraftor",
      locale: ogLocale(locale),
      type: "website",
    },
    twitter: {
      // Twitter image also derives from app/[locale]/opengraph-image.tsx.
      card: "summary_large_image",
      title: "ResumeCraftor - Professional Resume Builder",
      description: "Create professional, ATS-optimized resumes in minutes with ResumeCraftor.",
      site: "@resumecraftor",
      creator: "@resumecraftor",
    },
  };
}

export const viewport: Viewport = {
  themeColor: "#7c3aed",
  width: "device-width",
  initialScale: 1,
  colorScheme: "light",
};


import { AuthContext } from "@/context/AuthContext";
import { LazyAuthModal } from "@/components/auth/LazyAuthModal";
import { GlobalAnalytics } from "@/components/analytics/GlobalAnalytics";
import { Suspense } from "react";

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  // Enable static rendering for this locale.
  setRequestLocale(locale);

  const t = await getTranslations("Layout");

  return (
    <html lang={locale}>
      <head>
        {/* Google Tag Manager */}
        <Script id="gtm-init" strategy="afterInteractive" dangerouslySetInnerHTML={{ __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-5TQ4B5WN');` }} />
        {/* End Google Tag Manager */}
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2980943706375055"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Google Tag Manager (noscript) */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-5TQ4B5WN"
            height="0"
            width="0"
            style={{ display: 'none', visibility: 'hidden' }}
          />
        </noscript>
        {/* End Google Tag Manager (noscript) */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-[200] focus:rounded-lg focus:bg-purple-600 focus:px-4 focus:py-2 focus:text-white focus:font-bold"
        >
          {t("skipToContent")}
        </a>
        <NextIntlClientProvider>
          <AuthContext>
            <GlobalAnalytics />
            <div id="main-content" tabIndex={-1}>
              {children}
            </div>
            <Suspense fallback={null}>
              <LazyAuthModal />
            </Suspense>
          </AuthContext>
        </NextIntlClientProvider>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              "@id": "https://resumecraftor.com/#organization",
              "name": "ResumeCraftor",
              "url": "https://resumecraftor.com/",
              "description": "ResumeCraftor is an online resume and CV builder that helps users create professional, ATS-optimized resumes in minutes.",
              "logo": {
                "@type": "ImageObject",
                "url": "https://resumecraftor.com/logo.png",
                "width": 2238,
                "height": 2238
              },
              "image": "https://resumecraftor.com/og/og-image.png",
              "sameAs": [
                "https://www.youtube.com/@resumecraftor",
                "https://www.facebook.com/people/ResumeCraftor/61586853676415/",
                "https://www.instagram.com/resumecraftor26"
              ],
              "contactPoint": [
                {
                  "@type": "ContactPoint",
                  "contactType": "customer support",
                  "email": "support@resumecraftor.com",
                  "availableLanguage": ["en"],
                  "areaServed": "Worldwide"
                }
              ],
              "foundingDate": "2026",
              "areaServed": "Worldwide",
              "knowsAbout": [
                "Resume writing",
                "CV writing",
                "ATS optimization",
                "Job applications",
                "Career development",
                "Create resume",
                "Create CV"
              ]
            })
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              "@id": "https://resumecraftor.com/#website",
              "url": "https://resumecraftor.com/",
              "name": "ResumeCraftor",
              "inLanguage": locale,
              "publisher": {
                "@id": "https://resumecraftor.com/#organization"
              }
            })
          }}
        />
      </body>
    </html>
  );
}
